cookies/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

admin.autodiscover()

app_name = 'story9'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls'))
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    path('', views.story9, name='homepage'),
    path('login/', views.login_view, name ='login'),
    path('logout/', views.logout_view, name='logout'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='story9:login')
def story9(request):
    return render(request, 'homepage.html')

def login_view(request):
    text = ""
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('story9:homepage')
        else:
            text = "Oops, username or password is invalid!"
    else:
        if request.user.is_authenticated:
            return redirect('story9:homepage')
        else:
            form = AuthenticationForm()
    return render(request, 'login.html', {'form': form, 'text':text})

def logout_view(request):
    logout(request)
    return redirect('story9:login')

story9/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Welcome! </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous">
    <link
            href="https://necolas.github.io/normalize.css/latest/normalize.css"
            rel="stylesheet"/>
</head>

        <h1> Hey {{ user.username }}!</h1>
        <a type="button" class="btn btn-outline-info" href="{% url 'story9:logout' %}"> Log Out </a>

</body>
</html>

story9/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Logging in! </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous">
    <link
            href="https://necolas.github.io/normalize.css/latest/normalize.css"
            rel="stylesheet"/>
</head>
<body>
    <div class="wrapper">
    <form class="form-control" action="{% url 'story9:login' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <br/>
        <br/>
        <input class="btn btn-outline-info" type="submit" value="Login">
    </form>
    </div>
</body>
</html>